######################################################################
# Licensed Materials Property of HCL*
# (c) Copyright HCL Technologies Ltd. 2025. All rights reserved.
#
# * Trademark of HCL Technologies Limited
######################################################################
{{ $fullName := include "fullname" . }}
{{ $root := . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rag.deploymentName" . }}
  labels:
    app: "{{ .Values.app.name }}"
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: "{{ .Values.app.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.app.name }}"
    spec:
      securityContext:
{{- toYaml .Values.podSecurityContext | nindent 8 }}
{{ include "rag.pull.secret" . | indent 6 }}
{{ include "rag.serviceAccountName" . | indent 6 }}
      initContainers:
        - name: init-wait-for-vector-db
          image: busybox
          env:
{{- include "sltCommon.postgres.env.common" . | nindent 12 }}
          command: ['sh', '-c', 'until nc -z $POSTGRES_HOST:5432; do echo waiting for $POSTGRES_HOST:5432; sleep 30; done;']
        - name: init-create-postgres-user
          image: postgres:latest
          volumeMounts:
{{- include "rag.commonssl.volumeMounts.definition" . | nindent 12 }}
          env:
{{- include "sltCommon.postgres.env.common" . | nindent 12 }}
{{- include "sltCommon.postgres.env.password" . | nindent 12 }}
{{- include "sltCommon.postgres.env.adminpassword" . | nindent 12 }}
{{- include "sltCommon.init.postgres.certificate.env" . | nindent 12 }}
          command:
            - sh
            - -c
            - |
              if [ "$(PGPORT=$POSTGRES_PORT PGPASSWORD=$POSTGRES_ADMIN_PASSWORD psql -h $POSTGRES_HOST -U $POSTGRES_ADMIN_USER -tAc "SELECT 1 FROM pg_roles WHERE rolname='$POSTGRES_USER'")" != "1" ]; then
                PGPORT=$POSTGRES_PORT PGPASSWORD=$POSTGRES_ADMIN_PASSWORD psql -h $POSTGRES_HOST -U $POSTGRES_ADMIN_USER -c "CREATE USER \"$POSTGRES_USER\" WITH PASSWORD '$POSTGRES_PASSWORD';"
              else
                echo "User $POSTGRES_USER already exists"
              fi
        - name: init-create-db
          image: postgres:latest
          volumeMounts:
{{- include "rag.commonssl.volumeMounts.definition" . | nindent 12 }}
          env:
{{- include "sltCommon.postgres.env.common" . | nindent 12 }}
{{- include "sltCommon.postgres.env.password" . | nindent 12 }}
{{- include "sltCommon.postgres.env.adminpassword" . | nindent 12 }}
{{- include "sltCommon.init.postgres.certificate.env" . | nindent 12 }}
          command: ['sh', '-c', 'for DB in $POSTGRES_DB; do if ! PGPORT=5432 PGPASSWORD=$POSTGRES_ADMIN_PASSWORD psql "host=$POSTGRES_HOST user=$POSTGRES_ADMIN_USER" -lqt | cut -d \| -f 1 | grep -qw $DB; then PGPORT=5432 PGPASSWORD=$POSTGRES_ADMIN_PASSWORD psql "host=$POSTGRES_HOST user=$POSTGRES_ADMIN_USER" -c "CREATE DATABASE $DB WITH OWNER \"$POSTGRES_USER\" ENCODING=UTF8 TEMPLATE=template0;"; fi; PGPORT=5432 PGPASSWORD=$POSTGRES_ADMIN_PASSWORD psql "host=$POSTGRES_HOST user=$POSTGRES_ADMIN_USER dbname=$DB" -c "CREATE EXTENSION IF NOT EXISTS vector;"; done']
      containers:
        - name: "{{ .Chart.Name }}"
          image: {{ include "rag.registry" . }}/{{ .Values.container.image }}:{{ .Values.container.tag }}
          imagePullPolicy: {{ .Values.container.imagePullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "rag.configMapName" . }}
          env:
{{- include "rag.sofy.env.variables" . | indent 12 }}
            - name: NLTK_DATA
              value: /tmp/nltk_data
            {{- if (.Values.global.sofySolutionContext) }} 
            - name: OIDC_SERVER_URL
              value : https://sofy-kc.$(SOFY_HOSTNAME)/auth
            {{- else if .Values.authorization.oidcServerURL }}
            - name: OIDC_SERVER_URL
              value: {{ tpl .Values.authorization.oidcServerURL .}}
            {{- end }}
            {{- if .Values.sharedKeySecretName }}
            - name: SHARED_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ tpl .Values.sharedKeySecretName .}}
                  key: shared-key
            - name: SHARED_KEY_HEADER_KEY
              value:  "X-API-Key" 
            {{- end }}
            {{- range $key, $value := .Values.authorization.certs }}
            - name: {{ $key }}
              value: /opt/authcert/{{ lower $value }}.crt
            {{- end }}
            {{- range $key, $value := .Values.authorization.certs }}
            - name: {{ $key }}
              value: /opt/authcert/{{ lower $value }}.crt
            {{- end }}
            {{- range $key, $value := .Values.authorization.other }}
            - name: {{ $key }}
              value: {{ tpl $value $root }}
            {{- end }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /opt/apikey/gcp-vertexai-svc.json
{{- include "rag.commonssl.env.definition" . | indent 12 }}
{{- include "sltCommon.postgres.env.common" . | indent 12 }}
{{- include "sltCommon.postgres.env.password" . | indent 12 }}
          ports:
            - containerPort: {{ .Values.container.port }}
          volumeMounts:
{{- include "rag.commonssl.volumeMounts.definition" . | nindent 12 }}
            - name: nltk-data-dir
              mountPath: /tmp/nltk_data
            {{- range $key, $value := .Values.authorization.certs  }}
            - name: {{ lower $value }}-cert-volume
              mountPath: /opt/authcert/{{ lower $value }}.crt
              subPath: {{ lower $value }}.crt
              readOnly: true
            {{- end }}
            - name: certs-volumes
              mountPath: /opt/certs/
              readOnly: true
            - name: google-credentials
              mountPath: /opt/apikey/
              readOnly: true
          readinessProbe:
            tcpSocket:
              port: {{ .Values.probe.tcpSocket.port }}
            initialDelaySeconds: {{ .Values.probe.initialDelaySeconds }}
            periodSeconds: {{ .Values.probe.periodSeconds }}
            timeoutSeconds: {{ .Values.probe.timeoutSeconds }}
            successThreshold: {{ .Values.probe.successThreshold }}
            failureThreshold: {{ .Values.probe.failureThreshold }}
          resources:
            limits:
              cpu: "{{ .Values.resources.limits.cpu }}"
              memory: "{{ .Values.resources.limits.memory }}"
            requests:
              cpu: "{{ .Values.resources.requests.cpu }}"
              memory: "{{ .Values.resources.requests.memory }}"
      volumes:
{{- include "rag.commonssl.volume.definition" . | nindent 8 }}
        - name: nltk-data-dir
          emptyDir: {}
        - name: certs-volumes
          secret:
            secretName: {{ include "rag.cert.secret.name" . | quote }}
            defaultMode: 0644
            items:
              - key: tls.crt
                path: cert.pem
              - key: tls.key
                path: key.pem
              - key: ca.crt
                path: ca-cert.pem
        {{- range $key, $value := .Values.authorization.certs  }}
        - name: {{ lower $value }}-cert-volume
          secret:
            defaultMode: 0644
            secretName: {{ $value | quote }}
            items:
            - key: tls.crt
              path: {{ lower $value }}.crt
        {{- end }}
        - name: google-credentials
          secret:
            secretName: {{ .Release.Name }}-apikey-secret