# *******************************************************************************
# Licensed Materials - Property of HCL
# (c) Copyright HCL Technologies Ltd. 2024. All Rights Reserved.
# 
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule
# *******************************************************************************
{{ $fullName := include "aipilot.fullName" . }}

{{ $unoFullName := include "uno.fullname" . }}

apiVersion:  v1
kind:  ConfigMap
metadata: 
  name:  "{{ $fullName }}-{{ .Values.pilotActions.name }}-configmap"
data: 
{{- if .Values.pilotActions.config }}
{{ toYaml .Values.pilotActions.config | indent 2 }}
{{ end }}
  PILOT_BACKEND_URL: "https://{{ $fullName }}-{{ .Values.rag.app.name }}:9999"
  PILOT_NOTIFICATION_URL : https://{{ include "uno.fullname" . }}-pilot-notification:8443
  {{- if .Values.authorization.oidcServerURL }}
  OIDC_SERVER_URL: {{ .Values.authorization.oidcServerURL }}
  {{- end }}
  ENGINE_HOST: {{ .Values.global.uno.engineHost | default  (printf "%s-gateway" ($unoFullName))  }}
  ENGINE_PORT: {{ .Values.global.uno.enginePort | default 8443 | quote }}
  CERT_PATH: /var/actions-secret/ca.crt
  CERT_DIR: /etc/ssl/certs/
  SSL_CERT_FILE: /var/actions-secret/ca.crt
  SSL_CERT_DIR: /etc/ssl/certs/
  REQUESTS_CA_BUNDLE: /var/actions-secret/ca.crt
  JWT_PRIVATE_KEY_PEM_PATH: /var/actions-secret/tls.key
  