######################################################################
# Licensed Materials Property of HCL*
# (c) Copyright HCL Technologies Ltd. 2021, 2023. All rights reserved.
#
# * Trademark of HCL Technologies Limited
######################################################################
{{ $fullName := include "fullname" . }}
{{ $certIssuer := include "uno.cert.ingressControllerIssuer" . }}

{{- if .Values.ingress.enabled }}
{{- if .Values.config.multitenant.enabled }}


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-uno-ingress-tenantmanager
  labels:
{{ include "uno.common.label" . | indent 4 }}
  annotations:
    ingress.kubernetes.io/backend-protocol: HTTPS
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy_next_upstream_timeout : "180"
    nginx.ingress.kubernetes.io/proxy-body-size: 200m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
    nginx.ingress.kubernetes.io/proxy-request-buffering: 'off'
{{- if .Values.ingress.annotations }}
{{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ tpl $value $ | quote }}
{{- end }}
{{- end }}
{{- if not .Values.config.certificates.useCustomizedCert }} 
    cert-manager.io/issuer: {{ $certIssuer }}
{{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  tls:
    - hosts:
      - "tenantmanager{{.Values.ingress.baseDomainName }}"
      secretName: {{ $fullName }}-uno-tls-tenantmanager-secret
  rules:
    - host: tenantmanager{{.Values.ingress.baseDomainName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-tenantmanager
                port: 
                  number: 8443
{{- end }}
{{- end }}