######################################################################
# Licensed Materials Property of HCL*
# (c) Copyright HCL Technologies Ltd. 2021, 2023. All rights reserved.
#
# * Trademark of HCL Technologies Limited
######################################################################
{{ $fullName := include "fullname" . }}
{{ $certIssuer := include "uno.cert.ingressIssuer" . }}

{{- if .Values.ingress.enabled }}



apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-uno-ingress
  labels:
{{ include "uno.common.label" . | indent 4 }}
  annotations:
    ingress.kubernetes.io/backend-protocol: HTTPS
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy_next_upstream_timeout : "180"
    nginx.ingress.kubernetes.io/proxy-body-size: 200m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
    nginx.ingress.kubernetes.io/proxy-request-buffering: 'off'
{{- if .Values.ingress.annotations }}
{{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ tpl $value $ | quote }}
{{- end }}
{{- end }}
{{- if not .Values.config.certificates.useCustomizedCert }} 
    cert-manager.io/issuer: {{ $certIssuer }}
{{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  tls:
    - hosts:
    
{{- if .Values.config.multitenant.enabled }}
      - "*.{{.Values.deployment.console.ingressPrefix }}{{.Values.ingress.baseDomainName }}"
      - "*.{{.Values.deployment.gateway.ingressPrefix }}{{.Values.ingress.baseDomainName }}"
      - "*.{{.Values.deployment.agentmanager.ingressPrefix }}{{.Values.ingress.baseDomainName }}"
{{- else }}
      - {{.Values.deployment.console.ingressPrefix }}{{.Values.ingress.baseDomainName }}
      - {{.Values.deployment.gateway.ingressPrefix }}{{.Values.ingress.baseDomainName }}
      - {{.Values.deployment.agentmanager.ingressPrefix }}{{.Values.ingress.baseDomainName }}
{{- end }}
      secretName: {{ $fullName }}-uno-tls-secret
  rules:
{{- if .Values.config.multitenant.enabled }}
    - host: "*.{{.Values.deployment.console.ingressPrefix }}{{.Values.ingress.baseDomainName }}"
{{- else }}
    - host: {{.Values.deployment.console.ingressPrefix }}{{.Values.ingress.baseDomainName }}
{{- end }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
{{- if eq .Values.global.deploymentType  "aio" }}
                name: {{ $fullName }}-console-aio
{{- else }}
                name: {{ $fullName }}-console
{{- end }}
                port:
                  number: 8443
{{- if .Values.config.multitenant.enabled }}
    - host: "*.{{.Values.deployment.gateway.ingressPrefix }}{{.Values.ingress.baseDomainName }}"
{{- else }}
    - host: {{.Values.deployment.gateway.ingressPrefix }}{{.Values.ingress.baseDomainName }}
{{- end }}
      http:
        paths:
          - path: / 
            pathType: Prefix
            backend:
              service:
{{- if eq .Values.global.deploymentType  "aio" }}
                name: {{ $fullName }}-console-aio
{{- else }}
                name: {{ $fullName }}-gateway
{{- end }}
                port: 
                  number: 8443
{{- if .Values.config.multitenant.enabled }}
    - host: "*.{{.Values.deployment.agentmanager.ingressPrefix }}{{.Values.ingress.baseDomainName }}"
{{- else }}
    - host: {{.Values.deployment.agentmanager.ingressPrefix }}{{.Values.ingress.baseDomainName }}
{{- end }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
{{- if eq .Values.global.deploymentType  "aio" }}
                name: {{ $fullName }}-console-aio
{{- else }}
                name: {{ $fullName }}-agentmanager
{{- end }}
                port: 
                  number: 8443
  
{{- end }}

