######################################################################
# Licensed Materials Property of HCL*
# (c) Copyright HCL Technologies Ltd. 2021, 2023. All rights reserved.
#
# * Trademark of HCL Technologies Limited
######################################################################
{{ $fullName := include "fullname" . }}
{{ $saName := include "uno.serviceAccount" . }}

kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ $saName }}
{{- if ((.Values.config).serviceAccount).annotations }}
  annotations:
{{- range $key, $value := .Values.config.serviceAccount.annotations }}
    {{ $key }}: {{ tpl $value $ | quote }}
{{- end }}
{{- end }}
  labels:
{{ include "uno.common.label" . | indent 4 }}
imagePullSecrets:
  - name: sa-uno
  - name: sa-{{ .Release.Namespace }}
{{- if .Values.global.hclImagePullSecret }}
  - name: {{ .Values.global.hclImagePullSecret }}
{{- end }}


