######################################################################
# Licensed Materials Property of HCL*
# (c) Copyright HCL Technologies Ltd. 2020, 2025. All rights reserved.
#
# * Trademark of HCL Technologies Limited
######################################################################

apiVersion: v2
name: hcl-uno-engine-chart
description: A Helm chart for HCL Universal Orchestrator

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: "2.1.3"

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: "2.1.4.0-beta1"
kubeVersion: "=1.14.0 || >=1.14.0-0" 
maintainers:
  - name: HCL Tech Software
    url: https://www.hcltechsw.com/

dependencies:
  - name: hclaipilot
    version: 0.1.0
    repository: "file://charts/hcl-uno-aipilot"
    condition: global.enableUnoAIPilot
  
  - name: agentic-ai-builder
    version: 1.0.0
    alias: agenticAIBuilder
    repository: "file://charts/hcl-uno-agentic-ai-builder"
    condition: global.enableAgenticAIBuilder
